# Generated by Django 3.1.7 on 2021-03-05 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_history_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
